name: "Archive"
on:
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  Archive:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Download apk artifact
        uses: actions/download-artifact@v3
        with:
          name: apk-release-${{ github.event.pull_request.head.sha }}
          path: ./artifacts/wang.tato.webview.apk

      - name: Archive apk artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-release-${{ github.sha }}
          path: ./artifacts/wang.tato.webview.apk
