name: 'Build'
on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - 'v*'

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Setup Android SDK
        uses: amyu/setup-android@v3.1

      - name: Run build
        env:
          TATO_WEBVIEW_STORE_PASSWORD: ${{ secrets.TATO_WEBVIEW_STORE_PASSWORD }}
          TATO_WEBVIEW_KEY_ALIAS: ${{ secrets.TATO_WEBVIEW_KEY_ALIAS }}
          TATO_WEBVIEW_KEY_PASSWORD: ${{ secrets.TATO_WEBVIEW_KEY_PASSWORD }}
        run: ./gradlew assembleRelease

      - name: Archive apk artifact
        if: startsWith(github.ref, 'refs/tags/v') != true
        uses: actions/upload-artifact@v3
        with:
          name: apk-release-${{ github.sha }}
          path: ./app/build/outputs/apk/release/app-release.apk

      - name: Move file
        if: startsWith(github.ref, 'refs/tags/v')
        run: |
          mv ./app/build/outputs/apk/release/app-release.apk ./app/build/outputs/apk/release/wang.tato.webview_${{env.GITHUB_REF_NAME}}.apk

      - name: Release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          generate_release_notes: true
          files: ./app/build/outputs/apk/release/wang.tato.webview_${{env.GITHUB_REF_NAME}}.apk
